import { FontWeight } from "./types";

const palette = {
  white: "#FFFFFF",
  black: "#000000",
  slate950: "#040508",
  slate900: "#0B0C10",
  slate800: "#14161C",
  slate700: "#1F232B",
  slate600: "#2D333F",
  slate500: "#4B5563",
  slate400: "#9CA3AF",
  slate100: "#F3F4F6",
  gray50: "#F8FAFC",
  gray100: "#F1F5F9",
  gray200: "#E2E8F0",
  gray300: "#CBD5E1",
  gray400: "#94A3B8",
  gray500: "#64748B",
  gray600: "#475569",
  gray700: "#334155",
  gray800: "#1E293B",
  gray900: "#0F172A",
  brandCyan: "#00D2FF",
  brandBlue: "#3A7BD5",
  brandPurple: "#8E2DE2",
  brandPurpleDark: "#4A00E0",
  red500: "#F43F5E",
  green500: "#10B981",
  orange500: "#F59E0B",
  rgbBlack: "0, 0, 0",
  rgbWhite: "255, 255, 255",
};

const breakpoints = { mobile: "768px", tablet: "1024px" };

const media = {
  mobile: `@media (max-width: ${breakpoints.mobile})`,
  tablet: `@media (max-width: ${breakpoints.tablet})`,
  desktop: `@media (min-width: ${breakpoints.tablet})`,
};

const common = {
  spacing: {
    none: "0",
    "2xs": "2px",
    xs: "4px",
    sm: "8px",
    base: "12px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    "2xl": "48px",
    "3xl": "60px",
    "4xl": "72px",
  },
  borderRadius: {
    "2xs": "2px",
    xs: "4px",
    sm: "6px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    round: "9999px",
  },
  fontSizes: {
    "2xs": "0.625rem",
    xs: "0.75rem",
    sm: "0.875rem",
    base: "1rem",
    md: "1.125rem",
    lg: "1.25rem",
    xl: "1.5rem",
    "2xl": "1.875rem",
    "3xl": "2.25rem",
    "4xl": "3rem",
    "5xl": "3.75rem",
  },
  fontWeights: { regular: 400, medium: 500, bold: 700, extraBold: 800 },
  lineHeights: {
    tight: 1.2,
    normal: 1.4,
    comfortable: 1.5,
    relaxed: 1.6,
  },
  transitions: {
    duration: {
      fast: "150ms",
      normal: "200ms",
      slow: "400ms",
    },
    function: {
      default: "cubic-bezier(0.4, 0, 0.2, 1)",
      linear: "linear",
      easeInOut: "ease-in-out",
      easeOut: "ease-out",
      spring: "cubic-bezier(0.16, 1, 0.3, 1)",
      bounce: "cubic-bezier(0.87, 0, 0.13, 1)",
    },
  },
  zIndices: {
    sticky: 10,
    overlay: 1200,
    modal: 1300,
    alert: 1400,
    popover: 1500,
    toast: 1600,
    tooltip: 1700,
  },
  stateOpacity: {
    subtleBg: "1A", // 약 10% 투명도
    subtleBorder: "40", // 약 25% 투명도
    hoverBg: "26", // 약 15% 투명도
  },
  stateFilter: {
    hoverLighten: "brightness(1.1)", // 밝아짐
    hoverDarken: "brightness(0.9)", // 어두워짐
  },
};

export const sizes = {
  sidebarWidth: "240px",
  sidebarCollapsedWidth: "64px",
  headerHeight: "60px",
  control: {
    xs: "24px",
    sm: "32px",
    md: "40px",
    lg: "48px",
    xl: "56px",
  },
  icon: {
    xs: "12px",
    sm: "16px",
    md: "20px",
    lg: "24px",
    xl: "32px",
  },
  component: {
    checkbox: "20px",
    radio: "20px",
    radioIndicator: "10px",
    switch: {
      sm: { width: "32px", height: "16px", thumb: "12px", offset: "16px" },
      md: { width: "40px", height: "24px", thumb: "18px", offset: "16px" },
      lg: { width: "48px", height: "32px", thumb: "24px", offset: "16px" },
    },
    badgeMinHeight: "24px",
    emptyStateHeight: "120px",
    textareaMinHeight: "80px",
    dropdownMinWidth: "160px",
    selectViewportMaxHeight: "240px",
    tooltipMaxWidth: "240px",
    modalAlertWidth: "400px",
    datePickerModalWidth: "420px",
    modalDefaultWidth: "900px",
    tabFixedWidth: "120px",
    calendarDay: "32px",
    calendarHeaderLabelWidth: "100px",
    virtualRowHeight: 40,
    timeWheelHeight: "120px",
    timeWheelItemHeight: "40px",
    alertIcon: "56px",
    eventLineWidth: "16px",
    dividerThin: "1px",
    dividerMedium: "2px",
    overlayBlur: "4px",
  },
  offset: {
    popover: 8,
    tooltip: 4,
    toastGutter: 8,
  },
};

export const darkTheme = {
  ...common,
  mode: "dark" as const,
  media,
  sizes,
  colors: {
    background: {
      page: palette.slate950,
      surface: palette.slate900,
      modal: palette.slate800,
      input: palette.slate950,
      hover: palette.slate800,
      overlay: `rgba(${palette.rgbBlack}, 0.7)`,
      loadingOverlay: "rgba(11, 12, 16, 0.7)",
      scrollbar: palette.slate600,
      scrollbarHover: palette.brandPurple,
    },
    text: {
      primary: palette.white,
      secondary: palette.slate400,
      subtle: palette.slate400,
      disabled: palette.slate500,
      inverse: palette.slate900,
      mutedInverse: palette.slate400,
      brand: palette.brandCyan,
      success: palette.green500,
      danger: palette.red500,
      warning: palette.orange500,
    },
    border: {
      default: `rgba(${palette.rgbWhite}, 0.06)`,
      divider: `rgba(${palette.rgbWhite}, 0.06)`,
      subtle: `rgba(${palette.rgbWhite}, 0.04)`,
      strong: palette.slate500,
      focused: palette.brandCyan,
      inverse: `rgba(${palette.rgbWhite}, 0.2)`,
    },
    action: {
      primary: palette.brandBlue,
      primaryHover: palette.brandCyan,
      secondary: palette.slate700,
      secondaryBorder: palette.slate500,
    },
    status: {
      success: palette.green500,
      warning: palette.orange500,
      danger: palette.red500,
      info: palette.brandCyan,
      offline: palette.slate500,
    },
    statusBg: {
      success: `${palette.green500}1A`,
      warning: `${palette.orange500}1A`,
      danger: `${palette.red500}1A`,
      info: `${palette.brandCyan}1A`,
      offline: `${palette.slate500}1A`,
    },
    effect: {
      shadow: {
        base: `0 2px 8px rgba(${palette.rgbBlack}, 0.25)`,
        sm: `0 1px 2px rgba(${palette.rgbBlack}, 0.3)`,
        md: `0 4px 6px rgba(${palette.rgbBlack}, 0.4)`,
        lg: `0 10px 25px rgba(${palette.rgbBlack}, 0.5)`,
      },
      glow: "0 0 12px rgba(0, 229, 255, 0.4)",
    },
    brand: {
      primary: palette.brandBlue,
      primaryHover: palette.brandCyan,
      secondary: palette.green500,
      secondaryHover: palette.green500,
      accent: palette.orange500,
      accentSoft: palette.slate700,
      ink: palette.white,
      cyan: palette.brandCyan,
      purple: palette.brandPurple,
      gradient: null as string | null,
      textColor: palette.white,
      fontWeight: null as number | null,
    },
    surface: {
      canvas: palette.slate900,
      raised: palette.slate800,
      sunken: `rgba(${palette.rgbBlack}, 0.2)`,
      inverse: palette.slate950,
      panel: palette.slate800,
      overlay: `rgba(${palette.rgbBlack}, 0.7)`,
    },
    chart: {
      blue: palette.brandBlue,
      teal: palette.green500,
      coral: palette.red500,
      amber: palette.orange500,
      violet: palette.brandPurple,
      slate: palette.slate400,
    },
    utility: {
      transparent: "transparent",
      shadowColor: `rgba(${palette.rgbBlack}, 0.34)`,
      shadowStrongColor: `rgba(${palette.rgbBlack}, 0.5)`,
      canvasLine: `rgba(${palette.rgbWhite}, 0.22)`,
      canvasNode: "rgba(244, 244, 245, 0.86)",
      canvasGlow: "rgba(0, 210, 255, 0.3)",
    },
  },
};

export type ThemeType = Omit<typeof darkTheme, "mode"> & {
  mode: "dark" | "light";
};

export const lightTheme: ThemeType = {
  ...common,
  mode: "light",
  media,
  sizes,
  colors: {
    background: {
      page: palette.gray50,
      surface: palette.white,
      modal: palette.white,
      input: palette.white,
      hover: palette.gray100,
      overlay: `rgba(${palette.rgbBlack}, 0.4)`,
      loadingOverlay: `rgba(${palette.rgbWhite}, 0.7)`,
      scrollbar: palette.gray300,
      scrollbarHover: palette.brandBlue,
    },
    text: {
      primary: palette.gray900,
      secondary: palette.gray500,
      subtle: palette.gray500,
      disabled: palette.gray300,
      inverse: palette.white,
      mutedInverse: palette.gray300,
      brand: palette.brandPurpleDark,
      success: palette.green500,
      danger: palette.red500,
      warning: palette.orange500,
    },
    border: {
      default: palette.gray200,
      divider: palette.gray200,
      subtle: palette.gray100,
      strong: palette.gray400,
      focused: palette.brandBlue,
      inverse: `rgba(${palette.rgbWhite}, 0.22)`,
    },
    action: {
      primary: palette.brandBlue,
      primaryHover: palette.brandPurpleDark,
      secondary: palette.gray200,
      secondaryBorder: palette.gray300,
    },
    status: {
      success: palette.green500,
      warning: palette.orange500,
      danger: palette.red500,
      info: palette.brandBlue,
      offline: palette.gray400,
    },
    statusBg: {
      success: `${palette.green500}1A`,
      warning: `${palette.orange500}1A`,
      danger: `${palette.red500}1A`,
      info: `${palette.brandBlue}1A`,
      offline: `${palette.slate500}1A`,
    },
    effect: {
      shadow: {
        base: `0 2px 8px rgba(${palette.rgbBlack}, 0.1)`,
        sm: `0 1px 2px rgba(${palette.rgbBlack}, 0.05)`,
        md: `0 4px 6px -1px rgba(${palette.rgbBlack}, 0.1)`,
        lg: `0 10px 15px -3px rgba(${palette.rgbBlack}, 0.1)`,
      },
      glow: "0 0 12px rgba(58, 123, 213, 0.4)",
    },
    brand: {
      primary: palette.brandBlue,
      primaryHover: palette.brandPurpleDark,
      secondary: palette.green500,
      secondaryHover: palette.green500,
      accent: palette.orange500,
      accentSoft: palette.gray100,
      ink: palette.gray900,
      cyan: palette.brandCyan,
      purple: palette.brandPurple,
      gradient: null as string | null,
      textColor: palette.black,
      fontWeight: null as number | null,
    },
    surface: {
      canvas: palette.gray50,
      raised: palette.white,
      sunken: palette.gray100,
      inverse: palette.gray900,
      panel: palette.gray800,
      overlay: `rgba(${palette.rgbBlack}, 0.4)`,
    },
    chart: {
      blue: palette.brandBlue,
      teal: palette.green500,
      coral: palette.red500,
      amber: palette.orange500,
      violet: palette.brandPurpleDark,
      slate: palette.gray500,
    },
    utility: {
      transparent: "transparent",
      shadowColor: `rgba(${palette.rgbBlack}, 0.12)`,
      shadowStrongColor: `rgba(${palette.rgbBlack}, 0.22)`,
      canvasLine: `rgba(${palette.rgbWhite}, 0.34)`,
      canvasNode: `rgba(${palette.rgbWhite}, 0.9)`,
      canvasGlow: "rgba(58, 123, 213, 0.3)",
    },
  },
};

export const theme = darkTheme;
